services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: postgres:16.0-alpine
    restart: always
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: Kochoba
      POSTGRES_PASSWORD: example
      POSTGRES_DB: GenshinVybyu
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.1-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: